name: zuraffa
description: Installs zuraffa_ui engine components directly into your source code without depending on the package.
version: 0.0.0
repository: https://github.com/arrrrny/zuraffa_ui
topics:
  - user-interface
  - design-system
  - zuraffa-ui
  - material-alternative

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
# dependencies:

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^7.0.0
